name: flutter_loader
description: Provides widget for implementing UI with multiple states, i.e init, loading, error, loaded.
version: 0.1.0
homepage: https://github.com/rockerhieu/flutter_loader

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
