name: flutter_loader
description: A Flutter package for simplifying resource loading with customizable UI
version: 0.2.5
homepage: https://github.com/rockerhieu/flutter_loader

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
